### ISSUE TITLE
Decide what is new model version

### ISSUE THREAD

**Issue by aguschin** [iterative/mlem#119]
We've been considering that change in mlem.yaml introduces new model version. But if model description or tags ("image-classification", etc) change, this is not a new version.

- commit (doesn't change)
- meta file (doesn't change)
- parts of meta (including code in base64, can be cached as artifacts in future) (? what changes, what is not)
- artifacts (change)

As an option, we can have `.lock` file somewhere, then change in that file will indicate model version change. It can also store model version value.

Related though: would it be useful to have `mlem diff $MODEL_A $MODEL_B` for some reason?

**Comment by mike0sv** [comment]
Can we close this? @aguschin

**Comment by aguschin** [comment]
Not sure. My feeling is that we can need this for future integration with GTO.

**Comment by aguschin** [comment]
I think this is quite outdated now. We can reopen if it will be needed.
