### ISSUE TITLE
Fix serialisation in pandas for payload creation

### ISSUE THREAD

**Issue by madhur-tandon** [iterative/mlem#148]
While writing tests for `fastapi`, we needed to create payload for both `numpy` and `pandas` since the fixtures were parametrised. The expected column types for columns of the dataframe were `str` while they should have been `int`.

Reference: https://github.com/iterative/mlem/pull/145

**Comment by aguschin** [comment]
Not sure how much this can affect users. Setting p1, although could be p2.
