### ISSUE TITLE
Fix double deserialisation

### ISSUE THREAD

**Issue by madhur-tandon** [iterative/mlem#149]
While writing tests for fastapi here: https://github.com/iterative/mlem/pull/145

It is observed that deserialisation happens at two places:

- pydantic's internals turning payload into `response_model`
- call to `serializers[a.name].deserialize()` inside `fastapi.py`

I wonder if removing `parse_obj_as(response_model, response)` for the `handler()` function in `fastapi.py` fixes this?
We ideally need to ensure deserialisation happens in a single pass and in correct manner.

**Comment by aguschin** [comment]
closed by https://github.com/iterative/mlem/pull/308
