### ISSUE TITLE
Create more complex example for demo purposes

### ISSUE THREAD

**Issue by aguschin** [iterative/mlem#152]
Right now we have a toy example with a iris dataset and a simple ml model, deployed to heroku. Would be good to introduce more complex example which would show that MLEM is capable of real-world use.

```python
# E.g., one option is to convert model to `.onnx`
mlem pack modelpath out.onnx
# or deploy it in a server written in go
mlem deploy modelpath heroku --format=onnx --server=go
```

**Comment by mike0sv** [comment]
This feels outdated
