### ISSUE TITLE
Renaming modules inside /contrib

### ISSUE THREAD

**Issue by madhur-tandon** [iterative/mlem#154]
Currently we have module names that coincide with official library names.

So `mlem.contrib.numpy` clashes with official `numpy` for example.

This poses a problem when `numpy` is imported and is confused with the local module instead of the official one.

At some point, we should rename all these -- other examples include `pandas.py`, `sklearn.py`, etc.

Maybe @aguschin could suggest a good naming convention.

**Comment by mike0sv** [comment]
Should be fine without it unless you are running from `contrib` dir, which you should not do. Closing this for now
