### ISSUE TITLE
Add examples for calling servers to 'serve' cli/api

### ISSUE THREAD

**Issue by mike0sv** [iterative/mlem#189]
After #40 we can add some code to server startup (or somewhere else) like
```
# usage:
from mlem.... import Client

client = Client({host}, {port})
client.predict(...)
```

Also where applicable we can add non-python ways like adding curl examples for http servers

It would be super helpful if those examples would be generated dynamically with respect of the model we are serving (with the right payload) and could be just copy-pasted

**Comment by aguschin** [comment]
Done and can be found in https://mlem.ai/doc/user-guide/serving/
