### ISSUE TITLE
Setting up venv from `model.mlem` meta

### ISSUE THREAD

**Issue by aguschin** [iterative/mlem#209]
As @AlexIoannides suggested, there should be a way to install requirements from model metadata. 

Something like
```
$ mlem pack my-model requirements
catboost==1.0.0
numpy==2.0.0

$ mlem pack my-model requiments -c target requirements.txt
< output written to requirements.txt >
```
More advanced option would be to create venv right from mlem command: `$ mlem pack my-model venv -c target my-venv`, or create envs with Pipenv or Poetry.

**Comment by aguschin** [comment]
Can't find the ticket, but we were discussing creating `venv` from those requirements, like:

```shell
$ mlem create-venv s3://yourbucket/model
# or even
$ mlem serve s3://yourbucket/model --create-venv
```

**Comment by AlexIoannides** [comment]
@aguschin I think either of those options would be good.

**Comment by aguschin** [comment]
was competed in #434

**Comment by AlexIoannides** [comment]
Fantastic!
