### ISSUE TITLE
`mlem.api.ls` return type unclear

### ISSUE THREAD

**Issue by dberenbaum** [iterative/mlem#232]
I think it would be helpful to have `mlem.api.ls()` return something easier to read/parse, especially because:

* By default, mlem is now saving everything in `.mlem`, making it harder for users to see exactly what is saved and where.
* The docs start with an api-heavy workflow, so it will be important to see the available mlem objects from the api.

On a related note, since the docs start with the api, I think cleaning up `mlem.api.ls` and introducing this before the CLI command `mlem ls` might make more sense.

**Comment by mike0sv** [comment]
This got lost somehow, sorry. `ls` returns "mlem object type -> list of mlem objects" mapping. What is unclear and how can we improve?

**Comment by aguschin** [comment]
@dberenbaum, is this still needed?

**Comment by aguschin** [comment]
We removed `mlem.api.ls`, so I'm closing the issue.
