### ISSUE TITLE
Revisit `serve` / `apply-remote` workflow

### ISSUE THREAD

**Issue by daavoo** [iterative/mlem#241]
The API for `apply-remote` feels a little confusing to me, requiring to pass too much info and args:

```bash
mlem apply-remote http test_x.csv -c host="0.0.0.0" -c port=8080 --json
```

Given that we need to run first `mlem serve rf fastapi`, would be nice if I could somehow later reference (maybe adding a uid to each server?)  this server in a simpler way (haven't though in deep about UI):

```bash
# Could just generate a uid automatically (`rf-fastapi`) 
# and/or add a explicit `--name`/`--id` option? 
mlem serve rf fastapi
mlem apply-remote rf-fastapi test_x.csv  --json
```

---

Side note. `remote` sounds confusing to me as it's already used in iterative context for other meanings (i.e. DVC remote).

**Comment by aguschin** [comment]
@daavoo, do you have anything to add here? :)

Also looks like this is similar to https://github.com/iterative/mlem/issues/375
