### ISSUE TITLE
`mlem.api.save` fs argument type

### ISSUE THREAD

**Issue by mike0sv** [iterative/mlem#271]
Now it's `Union[str, AbstractFileSystem, None]`. But underlying implementation (in `MlemObject._parse_dump_args`) has it as `Optional[AbstractFileSystem]`. Need to either include `str` there (and corresponding logic) or  remove `str` from `save` signature

**Comment by madhur-tandon** [comment]
we can just remove `src` from `save` signature?
Just did that
