### ISSUE TITLE
Handle error on existing docker image

### ISSUE THREAD

**Issue by mike0sv** [iterative/mlem#278]
```
mlem build rf docker --conf server.type=fastapi --conf image.name=rf-image-test
⏳️ Loading model from .mlem/model/rf.mlem
💼 Adding model files...
🛠 Generating dockerfile...
💼 Adding sources...
💼 Generating requirements file...
🛠 Building docker image rf-image-test:latest...
❌ Unexpected error: Image rf-image-test:latest already exists at . Change name or set force_overwrite=True.
```
We need to make this "expected" error and also clarify how to set ow option
Reported by @drorata

**Comment by aguschin** [comment]
Long time no see.

I didn't find any option to build docker image "safely" at https://docs.docker.com/engine/reference/commandline/build/

My suggestion is to make this the same as in docker by default. Whoever wants this to be different, can set `--force_overwrite False`.
