### ISSUE TITLE
Using the mlem python api without running `mlem init` puts files in your cwd

### ISSUE THREAD

**Issue by dacbd** [iterative/mlem#293]
When you run code that uses the api functions like save, without first having run `mlem init` files are placed in your `cwd`

you can reproduce with the example repo with the following:
```bash
git clone git@github.com:iterative/example-mlem-get-started.git
cd ./example-mlem-get-started
rm -rf .mlem #simulate new project

virtualenv venv
source venv/bin/activate
pip install -r requirements.txt

mkdir temp
cd temp
python ../train.py
ls -l # see mlem objects
cd ..
python train.py
ls -l # see mlem objects
rm ./rf ./rf.mlem ./temp/*
mlem init
cd temp
python ../train.py
ls -l # mlem object in the correct place

```

**Comment by mike0sv** [comment]
Yeah, this is expected behavior. Not having .mlem directory means you don't have mlem project. In that case objects are saved at the path you provided

**Comment by mike0sv** [comment]
You can still access objects that you saved with "save(<path>)" with "load(<path>)" no matter if you have mlem project or not

**Comment by dacbd** [comment]
is cwd the best mechanism for that? or is `python ../train.py` to much of an edge case?

**Comment by aguschin** [comment]
IMO it makes sense to reproduce the behavior of `pickle.dump()` or `open()` here. If you check how it works, it uses cwd:

```python
# write.py
with open("tmp.txt", "w") as f:
    f.write("blah")
```
now
```shell
$ python write.py
$ cat tmp.txt
blah
```
and
```shell
$ mkdir tmp
$ cd tmp
$ python ../write.py
$ cat tmp.txt
blah
```

WDYT @dacbd?
