### ISSUE TITLE
support for dynamically shaped/sized symbolic data types 

### ISSUE THREAD

**Issue by maheshambule** [iterative/mlem#299]
Currently data types such as DictType, NumpyNdarrayType do not support dynamic size or shape. The types are bound to static data sources. This is problematic when inference output type size/shape can vary based on input size/shape. The onnx supports dynamically shaped/sized symbolic shapes. Similar kind of datatypes should also be supported in MLEM. The ONNX majorly supports NDArray tensor, sequence and map types. NDArray shape can have unknown or named values. Sequence and map does not have size attribute.  
Changes needed:
- NDArray equivalent NumpyNdarrayType can be modified to support unknown/dynamic values in its shape. Named values support can be added in future if need be. Currently first dimension is treated as unknown.
- Sequence equivalent ArrayType supports dynamic size. The size needs to be -1.
- Map equivalent DictType is hard to modify to support dynamic size because in current implementation the dataset is tightly bound with the DictType. The keys of dataset are part of DictType. Need to add new datatype for Dict.  Need to see how often maps with dynamic set of keys are used in real world models.

**Comment by mike0sv** [comment]
Rn numpy type has it's first shape element as `None`, which means any type. This way models can accept datasets of different sizes. If you specify all dimensions as `None`, this will mean dynamic shape. The only thing that will be not dynamic is number of dimensions. Is this not enough to support ONNX?

As for arrays and dicts I agree, we can add special size values for unbounded arrays and "unbounded" dicts (like ListType vs ArrayType, it will have arbitrary number of keys, but all values should be of the same type)

**Comment by mike0sv** [comment]
Can `shape=[3, None, None]` cover 1. and `shape=[1, None,4] cover 2.?
Can we use `shape=None` for A1? 
As for A3.2, where is this identifier used after? Can we drop it and just use A3.3 everywhere represented by `None`  as dimesion size?
