### ISSUE TITLE
Unable to resolve branch from URI when using mlem build on an mlem link, but only when commit sha is set as the rev in the link file. 

### ISSUE THREAD

**Issue by coltonflowers1** [iterative/mlem#396]
I am trying to build from a link in a private repo at a particular commit. Here is the link file contents:
```
link_type: model
object_type: link
path: .mlem/model/classifier.mlem
project: https://github.com/trend-community/mentalHealthClassification/
rev: ddcfa50b32367dffb2a970a99fa5b7dc577aa856
```
I run the following command: 
```
mlem build --conf package_name=mentalHealthClassification_model --conf target=build/ --conf version="v0.0.1" mentalHealthClassification whl
```
and get the following message
```
⏳️ Loading model from .mlem/link/mentalHealthClassification.mlem
🔗 Loading link to 
https://github.com/trend-community/mentalHealthClassification/tree/ddcfa50b32367dffb2a970a99fa5b7dc577aa856/.ml
em/model/classifier.mlem
❌ Could not resolve branch from uri 
"https://github.com/trend-community/mentalHealthClassification/tree/ddcfa50b32367dffb2a970a99fa5b7dc577aa856/.m
lem/model/classifier"
```
Removing the rev field in the link file resolves this issue, but I'd like to build from this specific commit. I did confirm "https://github.com/trend-community/mentalHealthClassification/tree/ddcfa50b32367dffb2a970a99fa5b7dc577aa856/.mlem/model/classifier.mlem" does exist. I am using MLEM 0.2.7.

**Comment by coltonflowers1** [comment]
I also just confirmed that I do not have this problem when using a tag or branch name instead of a commit sha in the _rev_ field.

**Comment by mike0sv** [comment]
can you run it `mlem --tb` flag and post outputs?

**Comment by mike0sv** [comment]
Can you try #401 and confirm that it works?

**Comment by aguschin** [comment]
Waiting for your confirmation to close this @coltonflowers1 :)

**Comment by aguschin** [comment]
Hi @coltonflowers1, I released this in MLEM 0.2.8 + Mike did some fixes after that PR, so you should check installing 0.2.8 (or installing directly from `main`).

**Comment by aguschin** [comment]
Closing this @coltonflowers1. Please reopen if that doesn't work for you :)

**Comment by coltonflowers1** [comment]
@aguschin Apologies, just now getting back to this. Trying the same command with MLEM 0.2.8 hangs on loading the link:

```
⏳️ Loading model from .mlem/link/mentalHealthClassification.mlem
🔗 Loading link to 
https://github.com/trend-community/mentalHealthClassification/tree/4824a139d98a3f4fbfb75a5709736544edb598a8/.mlem/model/classifier
.mlem
```
Again, no problem if I use a tag for the revision. I ran it with mlem --tb and there's no extra output.

**Comment by coltonflowers1** [comment]
@aguschin everything seems to be working. Thanks :)
