### ISSUE TITLE
Extra requirement found by `mlem.api.save`

### ISSUE THREAD

**Issue by aguschin** [iterative/mlem#418]
MLEM from `release/0.3.0` branch adds `dateutil` to requirements upon `mlem.api.save`:

```shell
$ git clone https://github.com/iterative/mlem
$ cd mlem
$ git checkout release/0.3.0
$ pip install -e .
$ python train.py
$ tail rf.mlem
object_type: model
requirements:
- module: sklearn
  version: 1.1.2
- module: pandas
  version: 1.5.0
- module: numpy
  version: 1.23.3
- module: dateutil
  version: 2.8.2
```

```python
# train.py
from mlem.api import save
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier


def main():
    data, y = load_iris(return_X_y=True, as_frame=True)
    rf = RandomForestClassifier(
        n_jobs=2,
        random_state=42,
    )
    rf.fit(data, y)

    save(
        rf,
        "rf",
        sample_data=data,
    )


if __name__ == "__main__":
    main()
```

Since it's not `dateutil`, but `python-dateutil`, due to another bug https://github.com/iterative/mlem/issues/362: not only `requirements` are incorrect, but also `mlem build` and `mlem deploy` don't work (pip can't find `pip install dateutil`).

Consequently, this also prevents generating `example-mlem-get-started` for the release https://github.com/iterative/mlem/issues/418

**Comment by mike0sv** [comment]
closed by #427 (reopen if not)
