### ISSUE TITLE
Security issue, possible to execute malicious code with api.apply

### ISSUE THREAD

**Issue by mmaruseru** [iterative/mlem#436]
It's possible to execute malicious code by creating a class with a predict method and pickling an instance of the class. The malicious code can be executed by using api.apply. In the code below is a working example.

mlem version: 0.2.8

```
import pickle
import numpy as np
import mlem
from pathlib import Path
from sklearn.linear_model import LinearRegression


class Malicious:
    @staticmethod
    def predict(x):
        print('Malicious code executing!')

        return np.zeros(7)


lin_model = LinearRegression()
lin_model.fit(np.ones((7, 5)), np.ones(7))
model_path = Path(__file__).parent / 'model'
mlem.api.save(lin_model, str(model_path), external=True, sample_data=np.ones((7, 5)))

malicious = Malicious()
with open(str(model_path), "wb") as output_file:
    pickle.dump(malicious, output_file)

pred = mlem.api.apply(str(model_path), np.ones((7, 5)), method='predict')
```

I know mlem is using pickle under the hood for saving models. But shouldn't there be a safeguard against the above example?

**Comment by aguschin** [comment]
@mike0sv, cc to you since you're our pickle 🥒 specialist

**Comment by mike0sv** [comment]
Hi @mmaruseru ! This is a known issue of pickle module. You dont even need to pickle malicious code, it can be added to existing functioning pickle dump (see https://github.com/mike0sv/nasty_pickle)
So we are doing the same thing as the whole python community and advise to only apply those models that you trust (like it says in [pickle module docs](https://docs.python.org/3/library/pickle.html))
The alternative would be to not use any pickle (and similar tools) at all, but that will limit MLEM functionality significantly
I am closing this for now, feel free to ask any questions though
