### ISSUE TITLE
HTTP clients for MLEM

### ISSUE THREAD

**Issue by denis-akvelon** [iterative/mlem#499]
Hi, guys!
Here are .NET and Java clients https://github.com/akvelon/MLEM-SDK-for-Java and https://github.com/akvelon/MLEM-SDK-for-C-Sharp that allow users to connect with MLEM API simply and easily, as well as integrate the MLEM model functionality to their .NET or Java project.
It would be great if you add links to them in your readme.

**Comment by shcheklein** [comment]
@denis-akvelon thanks! folks, I think it makes sense to include a section with libraries / integrations in the README and / or docs and add those links, wdyt? cc @jorgeorpinel

**Comment by jorgeorpinel** [comment]
We can def. mention these DSK in https://mlem.ai/doc/api-reference

**Comment by jorgeorpinel** [comment]
Hmmm no wait. I guess we're talking about something else. Maybe in https://mlem.ai/doc/user-guide/serving then?

**Comment by aguschin** [comment]
Hi @denis-akvelon. It look nice, thanks for all the work done!

If I get it right, it's an example how to use a MLEM model in Java/C-sharp. You hardcode the iris dataset and the model response format in it, thus it won't work for any MLEM model one can train - only for one that's trained in the current [Getting Started](https://mlem.ai/doc/get-started). Another MLEM model can have a different set of features, and a different format of input/output.

Do you have some scripts that generate this or have you written this manually? If you have those scripts, this can make a nice blog post on how to generate Java/C-sharp clients for a given MLEM model. We can help you with that.

As another option, maybe this can be integrated in MLEM as a plugin to generate these clients - I think @mike0sv can help us understand whether this is possible.

Considering what I said, how would you like to proceed with this? Write a blog post with this example, generalize it and share scripts to generate such clients, or consider implementing plugins to MLEM (if that's possible)?

**Comment by denis-akvelon** [comment]
Hi, @aguschin!
We hard-coded Iris model just for example. The MLEM client is implemented as generic class for Java/C# and hence applicable to any model - it's up to user to implement classes for input/response data.

Although we are thinking on upcoming feature - generating such classes based on model. For this feature we are working on separate module which generates such classes as output files, which can be integrated further into user app solution.

There are several data types supported at the moment (pandas dataframe, ndarray), but we are thinking about to add support for all data structure types which MLEM currently supports.

**Comment by denis-akvelon** [comment]
Hi, guys!
We released the next version of [.NET](https://github.com/akvelon/MLEM-SDK-for-C-Sharp) and [Java](https://github.com/akvelon/MLEM-SDK-for-Java) clients.
In the new version:
- Added support for list and str data types
- Made the API description public for the MLEM client
- Enhanced generation and validation of classes
- Enhanced default logging capabilities
- Examples have been added for other languages (F#, VB)

**Comment by aguschin** [comment]
Hi @denis-akvelon! Thanks, I'll take a look!

Do you guys do that for some project of yours at Akvelon? Would love to know more about how you use MLEM and what problems does it solve for you, what you like about it and what's missing!

If you'd prefer other means of communication to discuss this, we can use Discord (aguschin#7593) or telegram t.me/agusch1n

**Comment by denis-akvelon** [comment]
Hi, @aguschin!
We use your products (DVC and MLEM) in our client projects.
Our team has some suggestions, I will contact you via telegram.
