### ISSUE TITLE
README links are dead

### ISSUE THREAD

**Issue by chrisdonlan** [iterative/mlem#517]
The README links to the iterative documentation for Build, Deploy, etc. yield "Page Not Found" errors.

**Comment by shcheklein** [comment]
I think we forgot to add redirects. There is a `redirects.json` in all other projects that handles this.

**Comment by aguschin** [comment]
Thanks! Removed broken links for now. https://github.com/iterative/mlem/pull/518

I'll see about `redirects.json`.
