### ISSUE TITLE
Changing parameters of deployment isn't allowed

### ISSUE THREAD

**Issue by aguschin** [iterative/mlem#549]
If you created a deployment, but then trying to change it's params, MLEM won't allow you until you remove `.state` file:

```shell
$ mlem deploy run docker_container dc.mlem -m lyrics2emoji --image_name lyrics2emoji
deployed
$ mlem deploy remove dc
removed
$ rm dc.mlem
$ mlem -tb deploy run docker_container dc.mlem -m lyrics2emoji --image_name lyrics2emoji --ports.0 8080:8080
...
mlem.core.errors.DeploymentError: Deployment parameters changed, this is not supported yet. Please re-create deployment with new parameters
```

Until you realize you need to remove `dc.mlem.state` file you'll be getting this problems. You can need to use different  declaration files until you realize thet and delete them.

TBH I would expect it can be done even without `mlem deploy remove dc` and `rm dc.mlem`.

Can we enable this? So that running the deploy again will rewrite `dc.mlem` and re-deploy the model again?

```shell
$ mlem deploy run docker_container dc.mlem -m lyrics2emoji --image_name lyrics2emoji
deployed
$ mlem deploy run docker_container dc.mlem -m lyrics2emoji --image_name lyrics2emoji --ports.0 8080:8080
dc.mlem updated and service re-deployed
```

I understand this can be justified by usage safety - e.g. no way to redeploy a model with different params unless you know what you doing. But for novice users this can be a problem - they can skip MLEM because it's not intuitive here, I need to somehow figure out how do I redeploy my model, etc. Can be confusing.

**Comment by mike0sv** [comment]
Some parameters you can change and some you cant. For now we don't have a good method to differentiate them so we just forbid it altogether. However `mlem deploy remove` probably should purge the state with older declaration

**Comment by aguschin** [comment]
ok, so:
1. Let's remove state file on `mlem deploy remove`
2. This is tied together with https://github.com/iterative/mlem/issues/463, so let's continue addressing it there.
