### ISSUE TITLE
`deploy run heroku`: `--server` option is missing

### ISSUE THREAD

**Issue by aguschin** [iterative/mlem#568]
<img width="1524" alt="image" src="https://user-images.githubusercontent.com/6797716/212071224-282fd446-30de-46fb-bddc-59af8083772e.png">

Also don't see it in `declare`:
<img width="1536" alt="image" src="https://user-images.githubusercontent.com/6797716/212071420-9e69d113-0b6a-446b-8790-e6b083e75dfc.png">

At the same time, it's present for `kubernetes` and `docker_container` deployment targets. And is missing for `sagemaker`.

Is this some limitation of heroku and sagemaker?

**Comment by mike0sv** [comment]
For sagemaker - yes, it has it's own server implementation. For heroku - not neccessary, but heroku expects a web server to be running (same as flyio for example) so we can probably add that. However if server is not web-based, we should somehow warn the user about it

**Comment by aguschin** [comment]
I'd say we at least need to allow `streamlit` deployment to Heroku :) Otherwise all blog our posts will be about flyio... 😂
