### ISSUE TITLE
reset_index inside write method of PandasFormat class crashes the reader for stata format

### ISSUE THREAD

**Issue by aliahari** [iterative/mlem#618]
reset_index inside write method of PandasFormat class results in adding an index column with an empty label. This crashes the stata write method in pandas library which checks for the invalid column names. I am not sure why one needs to have reset_index method at all. It adds the index as a new column. Removing the function call to reset_index solves the issue

**Comment by aguschin** [comment]
Hi @aliahari! Thanks for reporting this! Could you please provide a code example to reproduce? Thanks!

**Comment by aliahari** [comment]
Hi, 
here is a sample code to reproduce the error
 ```python
target_file_name = "test.stata"
type_ = "pandas[stata]"
meta = mlem.api.import_object(
                    target_file_name, target= target_file_name, type_=type_, copy_data=True)
```
I have uploaded the simple stata file to [here](https://file.io/QFebRSu28wbf) but you can test it with any stata file.
