### ISSUE TITLE
`serve`: streamlit server fails with `PermissionError`

### ISSUE THREAD

**Issue by igordertigor** [iterative/mlem#656]
## Summary / Background
I'm trying to use `mlem serve streamlit` to deploy a demo server of a trained model, but I get a `PermissionError`. Here is code to replicate this:

1. I installed `pip install "mlem[streamlit]"
2. I have the following code in a file `create_model.py`:
```python
import mlem


def fake_model(x: float) -> float:
    return 2*x


mlem.api.save(fake_model, 'model', sample_data=3.)
```
3. I created the model by using `python create_model.py` and then run
```bash
$ mlem serve streamlit --model model
⏳️ Loading model from model.mlem
Starting streamlit server...
🖇️  Adding route for /__call__
Checkout openapi docs at <http://0.0.0.0:8081/docs>
INFO:     Started server process [296550]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.

Traceback (most recent call last):
  File "/home/xxx/.venv/bin/streamlit", line 8, in <module>
    sys.exit(main())
  File "/home/xxx/.venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/xxx/.venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/xxx/.venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/xxx/.venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/xxx/.venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/xxx/.venv/lib/python3.8/site-packages/streamlit/web/cli.py", line 209, in main_run
    _main_run(target, args, flag_options=kwargs)
  File "/home/xxx/.venv/lib/python3.8/site-packages/streamlit/web/cli.py", line 245, in _main_run
    bootstrap.run(file, command_line, args, flag_options)
  File "/home/xxx/.venv/lib/python3.8/site-packages/streamlit/web/bootstrap.py", line 404, in run
    asyncio.run(run_server())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/xxx/.venv/lib/python3.8/site-packages/streamlit/web/bootstrap.py", line 392, in run_server
    await server.start()
  File "/home/xxx/.venv/lib/python3.8/site-packages/streamlit/web/server/server.py", line 259, in start
    start_listening(app)
  File "/home/xxx/.venv/lib/python3.8/site-packages/streamlit/web/server/server.py", line 130, in start_listening
    start_listening_tcp_socket(http_server)
  File "/home/xxx/.venv/lib/python3.8/site-packages/streamlit/web/server/server.py", line 189, in start_listening_tcp_socket
    http_server.listen(port, address)
  File "/home/xxx/.venv/lib/python3.8/site-packages/tornado/tcpserver.py", line 183, in listen
    sockets = bind_sockets(
  File "/home/xxx/.venv/lib/python3.8/site-packages/tornado/netutil.py", line 162, in bind_sockets
    sock.bind(sockaddr)
PermissionError: [Errno 13] Permission denied
```
This may just be an easy fix in the documentation, but it may also be something deeper. I can't quite say. Am I doing something wrong? The documentation is relatively vague when it comes to the streamlit server.

**Comment by aguschin** [comment]
Yep, looks like it. It was selected to be 80 because this is a default port for streamlit apps https://docs.streamlit.io/library/advanced-features/configuration

**Comment by aminalaee** [comment]
And just to be clear, you want to explain this in the docs, right?
Or do you want to change the default ui port?

**Comment by aguschin** [comment]
I think this should be explained in the docs, here https://mlem.ai/doc/user-guide/serving/streamlit/
Btw, if you want, you can make a contribution, e.g. using "Edit on GH button" - then updating right markdown file, then CI will build a preview env for you to check. I'll help merging it.

But first I'd like to get a response from @igordertigor that the solution fixes his issue :)

**Comment by aminalaee** [comment]
Ah cool, I didn't know about that. Sure, I will do that.

And sorry to jump onto the issues in the project, I think you meant `ui_port` in your example to test, rather than `server_port` because the UI port is 80.

**Comment by aguschin** [comment]
Ah, right! Thanks @aminalaee! Let me fix my message above then to not get anyone confused!

**Comment by aguschin** [comment]
@igordertigor thanks! What would you like to see there, on documentation page?

**Comment by aguschin** [comment]
Good point, I think we need to document some options we have in `mlem serve streamlit -h`.

> By the way, would it be a useful alternative to add support for static files to the fastapi server? Then users could include their own javascript methods for a testing environment.

Could you please create a separate issue and describe your use case in more details? I also assume you need some specific way to add them so you'll be able to access those js methods - would be good to have some description of how you expect it to work / how you're doing it currently :) thanks!

**Comment by aguschin** [comment]
> customizing/embedding the streamlit code

@igordertigor, WDYM by embedding exactly - could you please clarify? Re customization - if you have a specific request, please submit is as an issue so we can keep track of it. Thanks :)

**Comment by igordertigor** [comment]
Hi @aguschin, no specific requests. I think I had seen a feature request somewhere with a request to add a streamlit component that could be used as part of a larger streamlit project. I just wanted to +1 that request although I don't need it right now and will likely not need it in the near future.

**Comment by aguschin** [comment]
Ok, got you. I think it was https://github.com/iterative/mlem/issues/529

Also curious - how do you use MLEM? I remember you submitting issues half a year ago or something. What's your use case?

**Comment by aguschin** [comment]
Thanks @igordertigor! Feel free to reach me out if you'll need something - will be curious to learn your feedback - what's your workflow, what works, what doesn't work. Closing this issue as completed thanks to https://github.com/iterative/mlem.ai/pull/343

**Comment by igordertigor** [comment]
Sure I will.
