### ISSUE TITLE
Bug: Mlem couldn’t fetch your accounts information

### ISSUE THREAD

**Issue by JamborJan** [iterative/mlem#683]
## Summary / Background
I want to login to my account on feddit.ch. The login seems to be successful but then an error occurs. The app tells me to file a bug, what I’m doing with this ticket.

I am using tags in my email as you can see I’m the screens. With `+lemmy`.

https://learn.microsoft.com/en-us/exchange/recipients-in-exchange-online/plus-addressing-in-exchange-online

![IMG_1632](https://github.com/iterative/mlem/assets/7508960/e9ce6c5d-caf1-4539-81d7-5bcca0cd540b)

![IMG_1630](https://github.com/iterative/mlem/assets/7508960/903984f5-c612-4c29-a021-bdefc03ac546)

**Comment by aguschin** [comment]
Hi! I guess you end up in the wrong place. This doesn't look like it's about MLEM.

**Comment by JamborJan** [comment]
Okay, that’s a way to see it. Buts it a rather useless answer. As Mlem is throwing the error a hint where to look would be nice. Or any other info so that people can find solutions.

**Comment by JamborJan** [comment]
Ooops, wrong Mlem. Sorry :)
