### ISSUE TITLE
Add CLI command to list versions of a specific model

### ISSUE THREAD

**Issue by aguschin** [iterative/mlem#94]
It may work like this (TODO: create more realistic example):
```shell
$ mlem versions data/model
- main: 
    - 27f5bae    aguschin    Fixing issue with probabilities
    - 1de6e4f    mike0sv     Training on larger dataset #185
    - 0.1.1      aguschin    Release: bump repo from 0.1.0 to 0.1.1
- feature/update-model
    - 9ab3d12    mike0sv     Try different approach on embedding generation
```

DVC does the same, need to check how.

**Comment by aguschin** [comment]
A note: this works in GTO: `gto show mymodel`. Not sure we need this in MLEM, although this looks cool IMO.

**Comment by mike0sv** [comment]
If we can do this only with mlem model being registered in gto, then we don't need this in mlem since user can do this with gto already.
Do we also want to allow users to do this without gto stuff?
